name: Sesnor simulation pipeline

on:
    push:
        branches:
            - main
            - 'feature/*'

jobs:
    generate:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v5

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'
                cache: 'pip'

            - name: Install requirements
              run: pip install -r requirements.txt

            - name : Run simulation script
              run: python ./src/simulation.py

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: measurements
                path: output/measurements.json
    test:
        runs-on: ubuntu-latest
        needs: [ generate ]

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v5

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'
                cache: 'pip'

            - name: Install requirements
              run: pip install -r requirements.txt

            - name: Download Artifact
              uses: actions/download-artifact@v5
              with:
                name: measurements
                path: measurements

            - name: print output
              run: ls -R measurements