name: Sensor simulation pipeline

on:
    push:
        branches:
            - main
            - 'feature/*'
    workflow_dispatch:

jobs:
    generate:
        continue-on-error: true
        strategy:
          matrix:
            sensors: [1, 2, 3]
            minutes: [1, 5, 10]
          max-parallel: 3
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v5

            - name: Setup Python & Install requirements
              uses: ./.github/actions/setup-env

            - name: Run simulation script
              env:
                sensors: ${{ matrix.sensors }}
                minutes: ${{ matrix.minutes }}
              run: python ./src/simulation.py

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: measurements_${{ matrix.sensors }}_${{ matrix.minutes }}
                path: output/measurements.json
    test:
        runs-on: ubuntu-latest
        needs: [ generate ]

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v5

            - name: Setup Python & Install requirements
              uses: ./.github/actions/setup-env

            - name: Download Artifact
              uses: actions/download-artifact@v5
              with:
                path: measurements

            - name: print output
              run: ls -R measurements

#           - name: Run tests
#             id: testscript

#           - name: Upload test report
#             if: steps.testscript.outcome == 'failure'
#             uses: actions/upload-artifact@v5
#             with:
#               name: test_report
#               path: test.json